server:
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: lbclock  #用于指定注册到EurekaServer 上的应用名称
  profiles:
    active: dev #切换配置文件
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
